name: Notice Notion Create PR
run-name: ${{ github.actor }} is updating Notion 📝
on:
  pull_request: 
    types: [opened]
jobs: 
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      
      - name: Move to the directory
        run: cd ActionScripts
      
      - name: Install dependencies
        run: npm install
      
      - name: Run the script
        run: node NoticeCreatePR.js